---------------------------------------------------- 
--Create Sequences
--Creates all needed sequences for ID incrementation 
----------------------------------------------------
CREATE SEQUENCE Category_Id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 9999 NOCACHE NOCYCLE;
CREATE SEQUENCE Subcategory_Id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 9999 NOCACHE NOCYCLE;
CREATE SEQUENCE Stock_Id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 9999 NOCACHE NOCYCLE;
CREATE SEQUENCE Employee_Number_seq INCREMENT BY 1 START WITH 1000 MAXVALUE 9999 NOCACHE NOCYCLE;
CREATE SEQUENCE Sale_Id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 9999 NOCACHE NOCYCLE;
CREATE SEQUENCE Sale_Item_Id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 9999 NOCACHE NOCYCLE;
CREATE SEQUENCE Client_Id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 9999 NOCACHE NOCYCLE;
CREATE SEQUENCE Equipment_Id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 9999 NOCACHE NOCYCLE;
CREATE SEQUENCE Job_Id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 9999 NOCACHE NOCYCLE;
CREATE SEQUENCE Job_Equipment_Id_seq INCREMENT BY 1 START WITH 1 MAXVALUE 9999 NOCACHE NOCYCLE;

